behaviors:
  RTSBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        gamma: 0.99
        strength: 0.5
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
        learning_rate: 3.0e-4
        # use_actions: false
        demo_path: Assets/Demonstrations/10t2.demo

    # behavioral_cloning:
    #   strength: 0.3
    #   demo_path: Assets/Demonstrations/10t2.demo
    #   steps: 150000

    max_steps: 10000000
    summary_freq: 2000
