behaviors:
  RTSBrain: # DİKKAT: Unity'deki Behavior Name burasıyla AYNİ OLMALI
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01 # Yüksek Entropy (0.01), ajanın 256 kareyi de denemesini teşvik eder.
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple # Grid Sensor için 'simple' genellikle yeterli ve hızlıdır.
      memory:
        sequence_length: 64 # ÖNEMLİ: Ajanın "Az önce kimi seçmiştim?" diye hatırlaması için hafıza şart.
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 5000
