behaviors:
  UnitSelector:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1 # Puanın önemi azaltıldı

      # GAIL İLE TEST (Daha stabil)
      # gail:
      #   strength: 0.5
      #   # strength: 1.5
      #   gamma: 0.999
      #   demo_path: Assets/Demonstrations/unitselrec4.demo
      #   use_actions: true # Action taklidi RTS için önemlidir
      #   use_vail: false
      #   network_settings:
      #     normalize: true
      #     hidden_units: 256
      #     num_layers: 3
      # learning_rate: 0.0001

    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 1000

  ActionSelector:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1
      # GAIL İLE TEST
      # gail:
      #   strength: 0.5
      #   # strength: 1.5
      #   gamma: 0.999
      #   demo_path: Assets/Demonstrations/actionselrec4.demo
      #   use_actions: true
      #   use_vail: false
      #   network_settings:
      #     normalize: true
      #     hidden_units: 256
      #     num_layers: 3
      # learning_rate: 0.0001

    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 1000

  TargetSelector:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1

      # GAIL İLE TEST
      # gail:
      #   strength: 0.5
      #   # strength: 1.5
      #   gamma: 0.999
      #   demo_path: Assets/Demonstrations/targetselrec4.demo
      #   use_actions: true
      #   use_vail: false
      #   network_settings:
      #     normalize: true
      #     hidden_units: 256
      #     num_layers: 3
      # learning_rate: 0.0001

    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 1000
