behaviors:
  RTSBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000000 # Adım sayısı artırıldı (5 ders olduğu için)
    time_horizon: 128
    summary_freq: 10000

environment_parameters:
  rts_level:
    curriculum:
      - name: Lesson0_Wood # DERS 0: Odun Topla
        completion_criteria:
          measure: reward
          behavior: RTSBrain
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.95 # 1.0 ödülün %95'ini alınca geç
        value: 0.0

      - name: Lesson1_Stone # DERS 1: Taş Topla
        completion_criteria:
          measure: reward
          behavior: RTSBrain
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.95
        value: 1.0

      - name: Lesson2_Meat # DERS 2: Et Topla
        completion_criteria:
          measure: reward
          behavior: RTSBrain
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.95
        value: 2.0

      - name: Lesson3_Builder # DERS 3: Kışla Yap
        completion_criteria:
          measure: reward
          behavior: RTSBrain
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.9 # 2.0 ödülün %95'i
        value: 3.0

      - name: Lesson4_General # DERS 4: Asker Üret (Final)
        value: 4.0
